# -*- coding: utf-8 -*-
"""Copia de practica-prof-Actividad 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V_UX-89ABW93nlrMd7VypA-fAChm3ugf

# Actividad 2

## Trabajo en grupo entre 2 o 3 estudiantes
Indicar los nombres y los links de los repositorios de la actividad 1 de los integrantes:
* Leandro Marcelino- repositorio:https://github.com/PokerMonkey12/mi_hobby
* Uziel Goral- repositorio:https://github.com/uzigoral/mi_hobby
* Ignacio Tessari- repositorio:https://github.com/IgnacioTessari/mi_hobby

# Python y Colab
* Se utilizará **Python** y este documento de **Google Colab** para resolver el ejercicio.
* Para que la tarea se considere entregada se deberá poner el link del documento colab, con las soluciones, en la tarea de **todos** los integrantes.

El ejercicio es **procesar texto** largo para identificar líenas, caracteres específicos.

1. Se deberá realizar una **copia** de este documento antes de comenzar a modificar
2. A lo largo del docuemnto se pedirá que responda preguntas y realice código, completar en la copia realizada con lo solicitado.
3. Copiar el texto de los archivos subidos en los repositorios individuales utilizados en la actividad 1,  de cada integrante de este grupo en una sola **variable de texto.**
"""

# completar con sus textos
texto_completo = ''' Título: Ver Películas:
Diversión: Disfruto ver películas porque me permite crear un momento de paz y tranquilidad con mi familia luego de que vengan del trabajo.

Familia: Mi hermano y yo compartimos este hobby mas que con el resto de la familia porque tenemos gustos parecidos aunque con el resto de la familia vemos peliculas los fines de semana.

Amigos: de vez en cuando me junto con unos amigos para ver peliculas wue elegimos entre todos.

Medios: Busco información sobre películas en youtube para ver reseñas y encontrar recomendaciones ademas, utilizo aplicaciones de streaming como Netflix y Disney+ para ver peliculas en cualquier momento.

Tecnología: La tecnología ha hecho que ver películas sea mas facil con las plataformas de streaming y las aplicaciones moviles se puedo ver peliculas en cualquier lugar que desee tambien es mucho mas facil compartir recomendaciones y discutir sobre las peliculas con amigos. gracias a el acceso a subtítulos y doblajes facilita que las películas sean accesibles para todas las personas siendo un hobby que puede ser disfrutado por personas de todos los géneros y la tecnología ha contribuido a hacerlo más accesible y diverso.

Titulo: Tocar la Guitarra
Diversión: Me gusta ya que con el paso del tiempo empezas a poder tocar las canciones que te gustan, asi tambien te ayuda a comprender un poco mejor la musica en general y conocer nuevos generos.

Familia: Comparto este hobby con mi papa que toca la bateria, gracias a el puedo tocar de vez en cuando con alguna otra banda.

Amigos: Si bien mis amigos tocan un poco el piano no compartimos mucho gusto musical asi que nunca tocamos.

Medios: Youtube es muy util para los tutoriales, asi tambien como internet en general para buscar canciones o paginas web para escribir partitura.

Tecnología: Si hablamos de guitarra electrica la tecnologia es indispensable y sin ella no existiria. Hoy en dia la mayoria de efectos para la guitarra son digitales y se manejan a traves de un programa. Y en cuanto genero, si bien un estudio reciente confirmo que el 50% de personas que compran guitarras son mujeres, en mi experiencia personal suelo ver muchos mas guitarristas hombres, y sinceramente no pude encontrar la razon.

Titulo: Jugar rugby.
Diversión: Lo hago desde los 4 años y considero que es parte de mi.

Familia: Con mis 2 hermanos mayores pero no jugamos en la misma categoria.

Amigos: No lo comparto con amigos pero si con compañeros los dias: martes, jueves y domingo.

Medios: Normalmente encuentro informacion de rugby por youtube e instagram.

Tecnología: La tecnologia ayudo a que se conozca mas y que haya mas publicidad, es realizado por mas hombres que mujeres.'''

"""* Utilice el método **split()** para separar las palabras de la variable texto_completo, guarde el resultado en una variable nueva.
* Indique el tipo de dato de la variable nueva utilizando el método **type(variable)**

* *texto en cursiva* Esta variable es de tipo **string**, podes conocer más en esta [página](https://docs.python.org/es/3/library/string.html).
* Podemos saber la longitud con len().
```python
len(texto_completo)
```
* Podemos separar por palabras, es decir, generar una lista donde cada palabra sea una elemento con el método split()
```python
texto_completo.split()
```
"""

palabras_separadas = texto_completo.split()
tipo_de_dato = type(palabras_separadas)

print("Palabras separadas:", palabras_separadas)
print("Tipo de dato de la variable nueva:", tipo_de_dato)

texto_ejemplo = '''Copiar el texto del archivo subido en los repositorios individuales de cada integrante de este grupo en una variable de texto'''
lista_palabras = texto_ejemplo.split()
print(lista_palabras)

#completar con el código que separa la variable texto_compelto teniendo en cuenta el caracter ":"
lista_palabras = texto_completo.split(":")
print(lista_palabras)
#completar con el código indicando la longitud de la nueva variable
longitud_lista = len(lista_palabras)
print("la longitud es de:",longitud_lista)

"""* Indique con qué método se puede sacar los espacios que tiene un texto adelante o atrás, como se ve en ejemplo de abajo.

"  texto con espacio             " -> "texto con espacio"
"""

#completar con el código ejemplo utilizando el método correspondiente
palabras_sin_espacio = texto_completo.strip()
print(palabras_sin_espacio)

"""* Indique cómo se puede utilizar el método split() para separar palabras, utilizando como caracter de separación, por ejemplo ":":

"texto: es una línea de texto" -> ["texto", "es una línea de texto"]
* Realice la separación del texto de la variable texto_completo y guarde el resultado en una nueva variable.
* Indique la longitud de esta nueva variable
"""

#completar con el código
texto_completo = ''' Título: Ver Películas:
Diversión: Disfruto ver películas porque me permite crear un momento de paz y tranquilidad con mi familia luego de que vengan del trabajo.

Familia: Mi hermano y yo compartimos este hobby mas que con el resto de la familia porque tenemos gustos parecidos aunque con el resto de la familia vemos peliculas los fines de semana.

Amigos: de vez en cuando me junto con unos amigos para ver peliculas wue elegimos entre todos.

Medios: Busco información sobre películas en youtube para ver reseñas y encontrar recomendaciones ademas, utilizo aplicaciones de streaming como Netflix y Disney+ para ver peliculas en cualquier momento.

Tecnología: La tecnología ha hecho que ver películas sea mas facil con las plataformas de streaming y las aplicaciones moviles se puedo ver peliculas en cualquier lugar que desee tambien es mucho mas facil compartir recomendaciones y discutir sobre las peliculas con amigos. gracias a el acceso a subtítulos y doblajes facilita que las películas sean accesibles para todas las personas siendo un hobby que puede ser disfrutado por personas de todos los géneros y la tecnología ha contribuido a hacerlo más accesible y diverso.

Titulo: Tocar la Guitarra
Diversión: Me gusta ya que con el paso del tiempo empezas a poder tocar las canciones que te gustan, asi tambien te ayuda a comprender un poco mejor la musica en general y conocer nuevos generos.

Familia: Comparto este hobby con mi papa que toca la bateria, gracias a el puedo tocar de vez en cuando con alguna otra banda.

Amigos: Si bien mis amigos tocan un poco el piano no compartimos mucho gusto musical asi que nunca tocamos.

Medios: Youtube es muy util para los tutoriales, asi tambien como internet en general para buscar canciones o paginas web para escribir partitura.

Tecnología: Si hablamos de guitarra electrica la tecnologia es indispensable y sin ella no existiria. Hoy en dia la mayoria de efectos para la guitarra son digitales y se manejan a traves de un programa. Y en cuanto genero, si bien un estudio reciente confirmo que el 50% de personas que compran guitarras son mujeres, en mi experiencia personal suelo ver muchos mas guitarristas hombres, y sinceramente no pude encontrar la razon.

Titulo: Jugar rugby.
Diversión: Lo hago desde los 4 años y considero que es parte de mi.

Familia: Con mis 2 hermanos mayores pero no jugamos en la misma categoria.

Amigos: No lo comparto con amigos pero si con compañeros los dias: martes, jueves y domingo.

Medios: Normalmente encuentro informacion de rugby por youtube e instagram.

Tecnología: La tecnologia ayudo a que se conozca mas y que haya mas publicidad, es realizado por mas hombres que mujeres. '''


#separar el texto en palabras usando split con el caracter ":"
txt = texto_completo.split(":")
print(txt)
#indicar la longitud de la nueva variable
print("la longitudes de:",len(txt))

"""También  se puede usar el método **splitlines()** para separar por cada nueva línea
```python
texto_ejemplo.splitlines()
```

* Generar una nueva variable que guarde el contenido de la variable texto_completo separandolo por nueva línea
* Recorrer la lista y encontrar los elementos que contienen el carater ":".
* Consulte la estructura **for** y el **if** en python.
"""

# ejemplo del uso del for
mi_lista =['a','b','c','d','e','f','g','h']
for i in mi_lista:
  print(i)

texto_completo = ''' Título: Ver Películas:
Diversión: Disfruto ver películas porque me permite crear un momento de paz y tranquilidad con mi familia luego de que vengan del trabajo.

Familia: Mi hermano y yo compartimos este hobby mas que con el resto de la familia porque tenemos gustos parecidos aunque con el resto de la familia vemos peliculas los fines de semana.

Amigos: de vez en cuando me junto con unos amigos para ver peliculas wue elegimos entre todos.

Medios: Busco información sobre películas en youtube para ver reseñas y encontrar recomendaciones ademas, utilizo aplicaciones de streaming como Netflix y Disney+ para ver peliculas en cualquier momento.

Tecnología: La tecnología ha hecho que ver películas sea mas facil con las plataformas de streaming y las aplicaciones moviles se puedo ver peliculas en cualquier lugar que desee tambien es mucho mas facil compartir recomendaciones y discutir sobre las peliculas con amigos. gracias a el acceso a subtítulos y doblajes facilita que las películas sean accesibles para todas las personas siendo un hobby que puede ser disfrutado por personas de todos los géneros y la tecnología ha contribuido a hacerlo más accesible y diverso.

Titulo: Tocar la Guitarra
Diversión: Me gusta ya que con el paso del tiempo empezas a poder tocar las canciones que te gustan, asi tambien te ayuda a comprender un poco mejor la musica en general y conocer nuevos generos.

Familia: Comparto este hobby con mi papa que toca la bateria, gracias a el puedo tocar de vez en cuando con alguna otra banda.

Amigos: Si bien mis amigos tocan un poco el piano no compartimos mucho gusto musical asi que nunca tocamos.

Medios: Youtube es muy util para los tutoriales, asi tambien como internet en general para buscar canciones o paginas web para escribir partitura.

Tecnología: Si hablamos de guitarra electrica la tecnologia es indispensable y sin ella no existiria. Hoy en dia la mayoria de efectos para la guitarra son digitales y se manejan a traves de un programa. Y en cuanto genero, si bien un estudio reciente confirmo que el 50% de personas que compran guitarras son mujeres, en mi experiencia personal suelo ver muchos mas guitarristas hombres, y sinceramente no pude encontrar la razon.

Titulo: Jugar rugby.
Diversión: Lo hago desde los 4 años y considero que es parte de mi.

Familia: Con mis 2 hermanos mayores pero no jugamos en la misma categoria.

Amigos: No lo comparto con amigos pero si con compañeros los dias: martes, jueves y domingo.

Medios: Normalmente encuentro informacion de rugby por youtube e instagram.

Tecnología: La tecnologia ayudo a que se conozca mas y que haya mas publicidad, es realizado por mas hombres que mujeres.'''
#completar acá con el código que permite separar por nueva línea la variable texto_completo, guarde el resultado en una nueva variable
txt = texto_completo.splitlines()
#recorrer  la nueva variable imprimiendo cada elemento de la lista
for I in txt:
  print(I)
longitud = len(txt)
print("la longitud es de:",longitud)
#indicar longitud de la nueva variable

"""## Contestar las siguientes consultas:
* ¿Qué elementos les parece que no sería necesario guardar en la lista?
---
* Respuesta:  no sería necesario guardar en la lista, todos aquellos que no contienen el carácter ":" ya que no tienen información relevante.
---
* ¿Todos los elementos, de la nueva variable que usó para guardar el resultado de separar por cada nueva línea, contienen texto?
---
* Respuesta: No todos los elementos de la nueva variable que contiene las líneas separadas contienen texto, algunas líneas pueden estar vacías.
---
* La estructura condicional de python  permite saber si un elemento de la lista, que se está recorriendo, contiene el caracter ":"?
---
* Respuesta: si lo permite
```python
if ":" in i:
      print("está")
```
* ¿Cómo se denomina la parte de la estructura condicional?
```python
":" in i
```
* Recorra la lista consultando si en la línea que se encuentra contiene el caracter ":"

"""

#completar con el código que recorre la variable lista e imprime por pantalla las líneas que contiene ":"
texto_completo = '''Leandro:
 Título: Ver Películas:
Diversión: Disfruto ver películas porque me permite crear un momento de paz y tranquilidad con mi familia luego de que vengan del trabajo.

Familia: Mi hermano y yo compartimos este hobby mas que con el resto de la familia porque tenemos gustos parecidos aunque con el resto de la familia vemos peliculas los fines de semana.

Amigos: de vez en cuando me junto con unos amigos para ver peliculas wue elegimos entre todos.

Medios: Busco información sobre películas en youtube para ver reseñas y encontrar recomendaciones ademas, utilizo aplicaciones de streaming como Netflix y Disney+ para ver peliculas en cualquier momento.

Tecnología: La tecnología ha hecho que ver películas sea mas facil con las plataformas de streaming y las aplicaciones moviles se puedo ver peliculas en cualquier lugar que desee tambien es mucho mas facil compartir recomendaciones y discutir sobre las peliculas con amigos. gracias a el acceso a subtítulos y doblajes facilita que las películas sean accesibles para todas las personas siendo un hobby que puede ser disfrutado por personas de todos los géneros y la tecnología ha contribuido a hacerlo más accesible y diverso.
Uziel:
Titulo: Tocar la Guitarra
Diversión: Me gusta ya que con el paso del tiempo empezas a poder tocar las canciones que te gustan, asi tambien te ayuda a comprender un poco mejor la musica en general y conocer nuevos generos.

Familia: Comparto este hobby con mi papa que toca la bateria, gracias a el puedo tocar de vez en cuando con alguna otra banda.

Amigos: Si bien mis amigos tocan un poco el piano no compartimos mucho gusto musical asi que nunca tocamos.

Medios: Youtube es muy util para los tutoriales, asi tambien como internet en general para buscar canciones o paginas web para escribir partitura.

Tecnología: Si hablamos de guitarra electrica la tecnologia es indispensable y sin ella no existiria. Hoy en dia la mayoria de efectos para la guitarra son digitales y se manejan a traves de un programa. Y en cuanto genero, si bien un estudio reciente confirmo que el 50% de personas que compran guitarras son mujeres, en mi experiencia personal suelo ver muchos mas guitarristas hombres, y sinceramente no pude encontrar la razon.
Ignacio:
Titulo: Jugar rugby.
Diversión: Lo hago desde los 4 años y considero que es parte de mi.

Familia: Con mis 2 hermanos mayores pero no jugamos en la misma categoria.

Amigos: No lo comparto con amigos pero si con compañeros los dias: martes, jueves y domingo.

Medios: Normalmente encuentro informacion de rugby por youtube e instagram.

Tecnología: La tecnologia ayudo a que se conozca mas y que haya mas publicidad, es realizado por mas hombres que mujeres. '''
lineas_separadas = texto_completo.splitlines()
for linea in lineas_separadas:
    if ":" in linea:
        print(linea)

"""1. Indicar qué tipos de datos se utilizaron en este documento.
2. Por cada tipo de datos de los ejemplos, indique cuáles son las variables utilizadas en esta actividad de ese tipo.
3. ¿Qué estructuras de datos que permite almacenar más de un elemento, utilizó en esta actividad? De los nombres de las variables que correspondan a este tipo de datos.
4. Investigar en chatgpt: ¿qué estructura podría ser más eficiente utilizar para guardar datos que estén relacionados entre sí y el acceso a ciertas claves sea directo sin tener que recorrer la estructura?
5. ¿Cómo se podría guardar los datos de los hobbies para poder acceder directamente a las respuestas de cada integrante? ¿qué estructura y cómo la armaría? Indicar cómo le quedaría sin hacerlo en python sino escribiendo la forma de cómo quedaría.

1. El tipo de dato utilizado en este documento fue de intigers, strings y listas de strings con: .split() y .splitlines()
---
2. Intigers: longitud_lista = len, len(txt), longitud = len(txt)

  Strings: texto_completo, texto_ejemplo
  
  Listas: palabras_separadas, lista_palabras, palabras_sin_espacio, txt, lineas_separadas
---
3. Las estructuras de datos que te permiten almacenar mas de un elemento fueron las listas (mi_lista =['a','b','c','d','e','f','g','h']) y los metodos .split() y .splitlines(), que funcionan creando listas a base de ciertas condiciones.
---
4. segun chatgpt Una estructura de datos que podría ser más eficiente para guardar datos
 relacionados entre sí y permitir un acceso directo a ciertas claves sin tener que recorrer toda la estructura es el diccionario en Python.

 En Python, un diccionario es una estructura de datos que almacena pares clave-valor, donde cada clave es única y se utiliza para acceder a su valor correspondiente de forma eficiente. Los diccionarios en Python están implementados con tablas hash, lo que proporciona un acceso rápido a los valores asociados a cada clave.

 Dado que los diccionarios utilizan tablas hash para almacenar los pares clave-valor, el acceso a los valores a través de las claves es casi instantáneo, incluso para grandes conjuntos de datos. Esto hace que los diccionarios sean ideales cuando necesitas una estructura de datos eficiente para buscar, insertar y eliminar elementos por clave.

 Aquí hay un ejemplo de cómo se utiliza un diccionario en Python:
```python
  # Crear un diccionario con datos relacionados
  datos = {
    "clave1": "valor1",
    "clave2": "valor2",
    "clave3": "valor3"
    }

  # Acceder a un valor directamente mediante su clave
  print(datos["clave2"])  # Imprime: valor2

  # Agregar un nuevo par clave-valor
  datos["clave4"] = "valor4"

  # Eliminar un par clave-valor
  del datos["clave1"]
```
 En este ejemplo, el acceso a los valores asociados a las claves se realiza directamente sin tener que recorrer toda la estructura del diccionario. Esto hace que los diccionarios sean una opción eficiente para almacenar datos relacionados cuando se necesita un acceso rápido a los valores por clave.
---
5. Podemos usar un diccionario para organizar los hobbies de cada persona. Cada amigo tiene su propia entrada en el diccionario, donde la clave es su nombre y el valor es una lista de sus hobbies. Esto nos permite acceder directamente a los hobbies de cualquier persona sin tener que revisar toda la lista de amigos.

## Tips de manejo de string
* Utiliza la función split() para dividir el texto en palabras. Por ejemplo, texto.split() devolverá una lista de palabras.

* Utiliza la función strip() para eliminar espacios en blanco al inicio y al final del texto. Por ejemplo, texto.strip() devolverá el texto sin espacios en blanco innecesarios.

* Utiliza el método splitlines() para dividir el texto en líneas. Por ejemplo, texto.splitlines() devolverá una lista de líneas.

* Utiliza el método replace() para reemplazar una subcadena por otra en un string. Por ejemplo, "Hola mundo".replace("mundo", "amigos") devolverá el string "Hola amigos".

* Utiliza el módulo string para manipular texto de forma eficiente. Por ejemplo, string.ascii_lowercase devolverá una cadena de texto con todas las letras minúsculas del alfabeto.

* Utiliza la función startswith() para comprobar si una cadena de texto empieza con un determinado prefijo. Por ejemplo, texto.startswith('Hola') devolverá True si el texto empieza con la palabra "Hola".

* Utiliza la función endswith() para comprobar si una cadena de texto termina con un determinado sufijo. Por ejemplo, texto.endswith('mundo') devolverá True si el texto termina con la palabra "mundo".

* Utiliza la función isalpha() para comprobar si una cadena de texto contiene solamente letras. Por ejemplo, texto.isalpha() devolverá True si el texto contiene solamente letras.

* Utiliza la función isdigit() para comprobar si una cadena de texto contiene solamente números. Por ejemplo, texto.isdigit() devolverá True si el texto contiene solamente números.
"""